apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: candela
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: us.gcr.io/microservices-kube/logger

